export const ADD_NODE = 'ADD_NODE'
export const DELETE_NODE = 'DELETE_NODE'
export const CHANGE_INCOME_INFO = 'CHANGE_INCOME_INFO'
export const UNREG_NODE = 'UNREG_NODE'
export const REG_NODE = 'REG_NODE'